apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f1vf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-f1vf@sha256:49268634d8c8598377cbb8f28a7c35e3d3fddaa2228daf7ef1f56526629ecc88
        name: my-nodejs
        resources: {}
status: {}
